<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.2.7</version>
	</parent>

	<groupId>za.co.yellowfire.threesixty</groupId>
	<artifactId>threesixty</artifactId>
	<version>24.0.0</version>
	<packaging>pom</packaging>

	<name>ThreeSixty</name>
	<description>360 review</description>

	<modules>
		<module>Country</module>
		<module>Web</module>
		<module>Assessment</module>
	</modules>

	<properties>
		<java.version>17</java.version>
		<vaadin.version>24.4.6</vaadin.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

		<sonar.organization>markash-github</sonar.organization>
		<sonar.host.url>https://sonarcloud.io</sonar.host.url>

		<sendgrid.version>4.3.0</sendgrid.version>
		<threesixty-components.version>0.3.2</threesixty-components.version>

		<vaadin-chartjs.version>1.4.0</vaadin-chartjs.version>
        <vaadin.version>24.4.4</vaadin.version>

		<vaadin-plugin.version>8.8.0.beta1</vaadin-plugin.version>
        <vaadin-icons.version>3.0.2</vaadin-icons.version>
        <vaadin4spring.version>2.0.0.RELEASE</vaadin4spring.version>
        <vaadin-springboot.version>24.4.4</vaadin-springboot.version>
		<vaadin-spring.version>24.4.4</vaadin-spring.version>

		<intellij.coverage.agent.version>1.0.746</intellij.coverage.agent.version>
		<intellij.agent.options>${project.basedir}/.qodana/code-coverage/output.ic,true,true,true,false</intellij.agent.options>

		<sonar.coverage.jacoco.xmlReportPaths>${project.basedir}/target/site/jacoco/jacoco.xml</sonar.coverage.jacoco.xmlReportPaths>
	</properties>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.sonarsource.scanner.maven</groupId>
					<artifactId>sonar-maven-plugin</artifactId>
					<version>4.0.0.4121</version>
				</plugin>
			</plugins>
		</pluginManagement>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>3.6.1</version>
				<executions>
					<execution>
						<id>intellij-coverage-agent</id>
						<phase>process-test-classes</phase>
						<goals>
							<goal>copy</goal>
						</goals>
						<configuration>
							<artifactItems>
								<!-- IntelliJ Coverage Agent -->
								<artifactItem>
									<groupId>org.jetbrains.intellij.deps</groupId>
									<artifactId>intellij-coverage-agent</artifactId>
									<version>${intellij.coverage.agent.version}</version>
									<destFileName>intellij-coverage-agent.jar</destFileName>
								</artifactItem>
							</artifactItems>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.2.5</version>
			</plugin>
		</plugins>
	</build>

	<profiles>
		<profile>
			<id>coverage</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.jacoco</groupId>
						<artifactId>jacoco-maven-plugin</artifactId>
						<version>0.8.12</version>
						<executions>
							<execution>
								<id>prepare-agent</id>
								<goals>
									<goal>prepare-agent</goal>
								</goals>
							</execution>
							<execution>
								<id>report</id>
								<goals>
									<goal>report</goal>
								</goals>
								<configuration>
									<formats>
										<format>XML</format>
									</formats>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>
