rating:
  question:
    lowerBound: 1
    upperBound: 5
    increment: 1
    locked: true

user:
  notification:
    limit: 10

threesixty:
  application:
    title: ThreeSixty
    logo: "<span class='v-icon v-icon-compile' style='font-family: Vaadin-Icons;'>&#xe6c8;</span>"
  mailing:
    provider: sendgrid
  badge:
    uri: "https://yellowfire-threesixty.herokuapp.com/api/badge/image"
  tracking:
    code: ${GOOGLE_TAG_CODE}
    url: www.threesixty.co.za

vaadin:
  servlet:
    production-mode: false

#threesixty.badge.uri=http://localhost:8080/api/badge/image

logging:
  level:
    org.springframework.web: INFO
    org.springframework.data: INFO
#    org.springframework.security: trace
#    com.azure.spring.cloud: trace
#    com.vaadin.flow.spring.security: trace
#    com.vaadin.flow.server.auth: trace
---
########################################################################################################################
# DEVELOPMENT
########################################################################################################################
#spring:
#  profiles: dev
#  data:
#    mongodb:
#      uri: "mongodb://127.0.0.1:27017/threesixty"
#server:
#  port: 8082

---
########################################################################################################################
# AZURE
########################################################################################################################
#spring:
#  profiles: azure
#server:
#  port: 9001
#
#logging:
#  level: DEBUG
#  level.org.springframework: DEBUG
#  file: /home/LogFiles/boot.log


########################################################################################################################
# HEROKU
########################################################################################################################


########################################################################################################################
# VAGRANT
########################################################################################################################

spring:
  jpa:
    defer-datasource-initialization: true
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: ${OID_CLIENT_ID}
            client-secret: ${OID_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - User.Read
              - openid
              - email
              - profile
            client-name: Microsoft
            client-alias: microsoft
        provider:
          azure:
            issuer-uri: ${OID_ISSUER_URI}
            user-name-attribute: name

server:
  port: 8080
  ssl:
    key-alias: localhost
    key-store: file:C://Source/Data/TrustStore/keyStore.p12
    key-store-password: ${KEY_STORE_PASSWORD:changeit}
    enabled: false
  servlet:
    session:
      timeout: 1m
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true