name: Build & Deploy

on:
  push:
    branches:
      - 24.0.0
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=ThreeSixty

      - name: Package
        run: mvn install -Pproduction

      - name: Upload web interface artifact
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: '${{ github.workspace }}/Web/target/*.jar'

      - name: Upload assessment service artifact
        uses: actions/upload-artifact@v4
        with:
          name: assessment
          path: '${{ github.workspace }}/Assessment/target/*.jar'

  webDeploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-web-to-webapp.outputs.webapp-url }}
      
    steps:
      - name: Download web artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: web
      
      - name: Deploy web to Azure Web App
        id: deploy-web-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Three60'
          slot-name: 'Production'
          package: '*.jar'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D5036CB1F23B458EB3B817F3A4AB50AB }}

  assessmentDeploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-assessment-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download assessment artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: assessment

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5368D1DF3B554FB0A3FA4F75145BC02A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1F2F12E8B92F4C1B8C42F719F7FC9BB1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_86112509979E4988BB293CD21C125435 }}

      - name: Deploy assessment artifact to Azure Web App
        id: deploy-assessment-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Three60-Assessment'
          slot-name: 'Production'
          package: '*.jar'